### get info
GET http://localhost:3000/api/currentUserInfo


### create user
POST http://localhost:3000/api/userAccount
Content-Type: application/json; charset=utf-8

{
    "firstName":"Stefan",
    "email":"hej@hopp.se",
    "password":"tjena123"
}

### login user
POST http://localhost:3000/api/signIn
Content-Type: application/json; charset=utf-8

{
    "email":"hej@hopp.se",
    "password":"tjena123"
}
